export const THEME_DETAILS = 'THEME_DETAILS';
export const HOME_BANNERS = 'HOME_BANNERS';
const CHANGE_CART_AMOUNT = "CHANGE_CART_AMOUNT";
export const BEST_SELLING = 'BEST_SELLING';
export const TOP_CATEGORIES = 'TOP_CATEGORIES';
export const TOP_RATINGS = 'TOP_RATINGS';
export const NEW_ARRIVALS = 'NEW_ARRIVALS';
export const BIG_DISCOUNTS = 'BIG_DISCOUNTS';

